### ISSUE TITLE
Github Actions CI pipeline with remote runner

### ISSUE THREAD

**Issue by alumarcu** [flix-tech/depcheck#6]
Currently we maintain the pipeline in GitLab. The pipeline runs on Python images that look like this:
```
FROM python:3.9-slim-bullseye

# Install environment dependencies
RUN apt-get update \
    && apt-get install -y curl git build-essential shellcheck \
    && curl -sSL https://install.python-poetry.org | python3 -

ENV PATH /root/.local/bin:${PATH}

# Remove the entrypoint
ENTRYPOINT []
```

A pipeline job looks like this in our private GitLab repo:
```
.test_default:
  stage: test
  before_script:
    - git clone -b ${GH_BRANCH} https://github.com/flix-tech/depcheck.git && cd depcheck
    - poetry install -n
  script:
    - poetry run coverage run --source depcheck -m pytest
    - poetry run pyre check
    - poetry run flake8 depcheck
    - poetry run isort depcheck --check-only
    - poetry run black depcheck --check
  variables:
    GH_BRANCH: master
```

It would be good to have a self-contained/open source pipeline, somewhere outside our private repos
